/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree.example;

public class App {
    public static Integer sum(Integer a, Integer b) {
        return a + b;
    }

    public static void main(String[] args) {
        var r = sum(18, 5);
        System.out.println(r);
    }
}
